import React from 'react';
import CodeBlock from '../../components/CodeBlock';
import Callout from '../../components/Callout';
import PageNav from '../../components/PageNav';
import { getAllPages } from '../../config/navigation';

const pages = getAllPages();
const currentIdx = pages.findIndex(p => p.id === 'ncs-recurring');
const prevPage = pages[currentIdx - 1];
const nextPage = pages[currentIdx + 1];

const recurringCode = `// Step 1: Save payment method at initial checkout
SessionCreateParams params = SessionCreateParams.builder()
    .setMode(SessionCreateParams.Mode.PAYMENT)
    .setSuccessUrl(successUrl)
    .setCancelUrl(cancelUrl)
    .setPaymentIntentData(
        SessionCreateParams.PaymentIntentData.builder()
            .setSetupFutureUsage(
                SessionCreateParams.PaymentIntentData.SetupFutureUsage.OFF_SESSION)
            .build())
    .build();

// Step 2: Charge the saved payment method later (off-session)
PaymentIntentCreateParams chargeParams = PaymentIntentCreateParams.builder()
    .setAmount(amountCents)
    .setCurrency("sgd")
    .setCustomer(customerId)
    .setPaymentMethod(paymentMethodId)
    .setConfirm(true)
    .setOffSession(true)
    .build();

PaymentIntent.create(chargeParams);`;

const tableRows = [
  { feature: 'Who controls the schedule', sfuValue: 'Your application', billingValue: 'Stripe' },
  { feature: 'Billing trigger', sfuValue: 'Your code calls the API', billingValue: 'Automatic on schedule' },
  { feature: 'Customer-facing invoice', sfuValue: 'Manual / custom', billingValue: 'Auto-generated by Stripe' },
  { feature: 'Trial periods', sfuValue: 'Manual logic', billingValue: 'Built-in' },
  { feature: 'Best for', sfuValue: 'Gov fee collection, ad-hoc charges', billingValue: 'Recurring subscriptions, SaaS' },
  { feature: 'Complexity', sfuValue: 'Lower', billingValue: 'Higher setup, lower ongoing' },
];

export default function RecurringBilling() {
  return (
    <div>
      <div className="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold mb-4" style={{ backgroundColor: '#E0F2FE', color: '#0570DE' }}>
        NCS: iConnect Workshop
      </div>
      <h1 className="text-3xl font-bold mb-2" style={{ color: '#0A2540' }}>Recurring & Scheduled Payments</h1>
      <p className="text-lg mb-4" style={{ color: '#425466' }}>
        Two patterns for repeat billing — choose based on who controls the schedule.
      </p>

      <p className="text-sm mb-6" style={{ color: '#425466' }}>
        Not all government or enterprise payment needs are one-time. School fee collections, maintenance contracts, and subscription-based service access all require repeat charges. Stripe supports two patterns — which one fits depends on who controls when charges happen.
      </p>

      <h2 className="text-xl font-semibold mb-3" style={{ color: '#0A2540' }}>Pattern Comparison</h2>
      <div className="rounded-xl border mb-6 bg-white overflow-x-auto" style={{ borderColor: '#E6EBF1' }}>
        <table className="w-full text-sm">
          <thead>
            <tr style={{ borderBottom: '1px solid #E6EBF1' }}>
              <th className="text-left p-3 font-semibold" style={{ color: '#0A2540' }}>Feature</th>
              <th className="text-left p-3 font-semibold" style={{ color: '#0A2540' }}>setup_future_usage</th>
              <th className="text-left p-3 font-semibold" style={{ color: '#0A2540' }}>Stripe Billing</th>
            </tr>
          </thead>
          <tbody style={{ color: '#425466' }}>
            {tableRows.map(({ feature, sfuValue, billingValue }, i) => (
              <tr key={feature} style={{ borderBottom: i < tableRows.length - 1 ? '1px solid #E6EBF1' : undefined }}>
                <td className="p-3 font-medium" style={{ color: '#0A2540' }}>{feature}</td>
                <td className="p-3">{sfuValue}</td>
                <td className="p-3">{billingValue}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 className="text-xl font-semibold mb-2" style={{ color: '#0A2540' }}>Pattern 1 — setup_future_usage (save & charge later)</h2>
      <p className="text-sm mb-3" style={{ color: '#425466' }}>
        The customer authorises their card or bank account once. Your application saves the payment method and charges it later on your schedule. The NCS application decides when to charge — Stripe just executes the charge when told.
      </p>
      <CodeBlock language="java" filename="RecurringPaymentService.java" code={recurringCode} />

      <h2 className="text-xl font-semibold mb-2 mt-6" style={{ color: '#0A2540' }}>Pattern 2 — Stripe Billing (subscription-driven)</h2>
      <p className="text-sm mb-4" style={{ color: '#425466' }}>
        Stripe owns the billing schedule. You define a Product and Price (e.g. "Annual maintenance fee — SGD 1,200/year"), attach a customer, and Stripe automatically charges and sends invoices on the schedule. Your application just responds to webhook events.
      </p>

      <Callout type="info" title="Which pattern for SSOE?">
        If SSOE collects school fees on set dates (e.g. term start), <code>setup_future_usage</code> is simpler — MOE controls when charges run. Stripe Billing suits subscription-style access fees where Stripe should own the schedule and invoice generation automatically.
      </Callout>

      <PageNav prevPage={prevPage} nextPage={nextPage} />
    </div>
  );
}
